import type { Metadata } from "next";
import { ThemeProvider } from "@/components/themeProvider/themeProvider";
import Header from "@/components/header";
import Footer from "@/components/footer";
import "../styles/globals.scss";

export const metadata: Metadata = {
  title: "Maple",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet" />
      </head>
      <body suppressHydrationWarning>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <Header />
          <main className="container flex flex-col justify-center items-center min-h-[calc(100vh-200px)] mx-auto my-8 p-4 shadow-md rounded-lg bg-background text-foreground">
            {children}
          </main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
